 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */11 * * *'
   workflow_dispatch:
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: jasineri/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: DropFan
            # Text on contribution graph 
            text: I'mTiger
       - run: |
          git config --global user.name 'Tiger'
          git config --global user.email 'DropFan@Gmail.com'
          git commit -am 'gitartwork action'
          git push
